In [42]:
from skimage import io,data,transform
import numpy as np
import matplotlib.pyplot as plt
#目标大小
IMG_SIZE = 32
def translate(image_path,IMG_SIZE):
    #读入图片并变成灰色
    img = io.imread(image_path, as_grey=True)
    #缩小到28*28
    translated_img = transform.resize(img, (IMG_SIZE, IMG_SIZE))
    #变成1*784的一维数组
    flatten_img = np.reshape(translated_img, IMG_SIZE*IMG_SIZE)
    #mnist数据集中1代表黑，0代表白
    result = np.array([flatten_img])
    #返回该图的所代表的向量
    return result

In [45]:
image_path=r"D:\Jupyter\Machine-Learning-master\kNN\3.数字识别\mnist database\9\mnist_train_45.png"
img_vector=translate(image_path,32)
print(img_vector)

[[0. 0. 0. ... 0. 0. 0.]]


D:\anaconda3\lib\site-packages\skimage\transform\_warps.py:105: UserWarning: The default mode, 'constant', will be changed to 'reflect' in skimage 0.15.
  warn("The default mode, 'constant', will be changed to 'reflect' in "
D:\anaconda3\lib\site-packages\skimage\transform\_warps.py:110: UserWarning: Anti-aliasing will be enabled by default in skimage 0.15 to avoid aliasing artifacts when down-sampling images.
  warn("Anti-aliasing will be enabled by default in skimage 0.15 to "


In [46]:
print(len(img_vector[0]))

1024


In [47]:
from sklearn.externals import joblib

#加载和使用模型
RF=joblib.load(r"D:\Jupyter\Machine-Learning-master\kNN\3.数字识别\knn_digital_recognition.model")

a=[]
count=0
img_vector_1=[]
for b in img_vector[0]:
    if float(b)<=0.035295:
        b=0
    else:
        b=1
    img_vector_1.append(b)
#     print(b)
    a.append(b)
    count+=1
    if count%32==0:
        print(np.array(a))
        a.clear()
# print(img2vector(file_name)[1])
# thsDoc=[img2vector(file_name)[0],[img2vector(file_name)[1]]]
result=RF.predict([img_vector_1])
# print(x_test)
# print(RF.score(x_test, y_test))
# print(y_test)
print(result)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0